//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Menu.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OtomasyonEntities : DbContext
    {
        public OtomasyonEntities()
            : base("name=OtomasyonEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SonSatisler> SonSatisler { get; set; }
        public virtual DbSet<UrunListesi> UrunListesi { get; set; }
        public virtual DbSet<VeresiyeListesi> VeresiyeListesi { get; set; }
    }
}
